Emoji plot
joweich/chat-miner pull request #88
Opened 2023-02-18 00:18 UTC by lsomm

Hi, this is the PR to issue #61

2023-02-18 19:16 UTC, joweich requested changes
@lsomm many thanks and congratulations to your first PR!
Added some comments that mainly concern code cleaning and code style. 
Would definitely recommend using code linters (pylint, flake8, ...) and an automatic code formatter (black).
Let me know if I can support you with further guidance! :+1:

2023-02-18 19:16 UTC, joweich commented on chatminer/visualizations.py
> +    return freqs.plot.pie()
The other visualizations provide the option to hand over the matplotlib axis as a parameter (`ax=None`) and fallback to a default axis via
```
if ax is None:
        _, ax = plt.subplots()
```
I would see this for the piechart as well to be well aligned to the other plots.

2023-02-25 23:31 UTC, lsomm commented
Thank you so much for the comments! I'll look to it after my exams :-)

2023-06-08 01:03 UTC, joweich commented
@lsomm are you working on this? :slightly_smiling_face:

2023-07-09 11:36 UTC, lsomm commented
Hi, sorry for staying under the radar for so long. Long story short: I might, not now though. If you want to close the PR, thats fine for me.

2023-07-12 13:40 UTC, joweich commented
> Hi, sorry for staying under the radar for so long. Long story short: I might, not now though. If you want to close the PR, thats fine for me. 

@lsomm got you! I will close this for now but happy to reopen it once you get the chance to finish it!
Btw, we have several other open issues if you want to work on something else 🙂

2023-07-12 13:41 UTC, closed without merging